[project]
name = "timelock-heuristic"
authors = ["Alice Thompson"]
description = "A smart contract implementing a flexible and secure timelock mechanism for token distribution and governance"
telemetry = false
requirements = []
[contracts.timelock-core]
path = "contracts/timelock-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
